/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/context": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Context */
        get: operations["get_context_context_get"];
        /** Put Context */
        put: operations["put_context_context_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/context/scan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Scan Context */
        post: operations["scan_context_context_scan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{export_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Export */
        get: operations["download_export_exports__export_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session Endpoint */
        post: operations["create_session_endpoint_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Session Endpoint */
        get: operations["get_session_endpoint_sessions__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/approve-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve Session Intent Endpoint */
        post: operations["approve_session_intent_endpoint_sessions__session_id__approve_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Session Export Endpoint */
        post: operations["create_session_export_endpoint_sessions__session_id__export_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Session Message Endpoint */
        post: operations["add_session_message_endpoint_sessions__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/prepare-sql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Prepare Session Sql Endpoint */
        post: operations["prepare_session_sql_endpoint_sessions__session_id__prepare_sql_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sessions/{session_id}/propose-intent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Propose Session Intent Endpoint */
        post: operations["propose_session_intent_endpoint_sessions__session_id__propose_intent_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/database/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Database Settings Endpoint */
        post: operations["test_database_settings_endpoint_settings_database_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings/model-provider": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Model Provider Settings Endpoint */
        get: operations["get_model_provider_settings_endpoint_settings_model_provider_get"];
        /** Put Model Provider Settings Endpoint */
        put: operations["put_model_provider_settings_endpoint_settings_model_provider_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/bootstrap": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Bootstrap Setup Endpoint */
        post: operations["bootstrap_setup_endpoint_setup_bootstrap_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Setup Status Endpoint */
        get: operations["get_setup_status_endpoint_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CSVColumnIntent */
        CSVColumnIntent: {
            /** Description */
            description: string;
            /** Name */
            name: string;
            /** Source Hint */
            source_hint?: string | null;
        };
        /** CSVIntent */
        CSVIntent: {
            /** Assumptions */
            assumptions?: string[];
            /** Columns */
            columns: components["schemas"]["CSVColumnIntent"][];
            /** Derived Fields */
            derived_fields?: string[];
            /** Filters */
            filters?: string[];
            /**
             * Max Row Count
             * @default 1000
             */
            max_row_count: number;
            /** Row Meaning */
            row_meaning: string;
            /** Summary */
            summary: string;
        };
        /** CSVIntentProposal */
        CSVIntentProposal: {
            intent?: components["schemas"]["CSVIntent"] | null;
            /** Message */
            message: string;
            /** Questions */
            questions?: string[];
        };
        /** ChatMessage */
        ChatMessage: {
            /** Content */
            content: string;
            /** Role */
            role: string;
        };
        /** ContextDocument */
        ContextDocument: {
            /** Context */
            context: string;
            policy: components["schemas"]["ContextPolicy"];
            schema: components["schemas"]["SchemaContext"];
        };
        /** ContextPolicy */
        ContextPolicy: {
            /** Blocked Columns */
            blocked_columns?: string[];
            /** Blocked Functions */
            blocked_functions?: string[];
            /** Blocked Schemas */
            blocked_schemas?: string[];
            /** Blocked Tables */
            blocked_tables?: string[];
            /**
             * Lock Timeout Ms
             * @default 5000
             */
            lock_timeout_ms: number;
            /**
             * Max Export Bytes
             * @default 50000000
             */
            max_export_bytes: number;
            /**
             * Max Row Count
             * @default 100000
             */
            max_row_count: number;
            /**
             * Statement Timeout Ms
             * @default 30000
             */
            statement_timeout_ms: number;
        };
        /** ContextScanResponse */
        ContextScanResponse: {
            /** Column Count */
            column_count: number;
            /** Context */
            context: string;
            policy: components["schemas"]["ContextPolicy"];
            schema: components["schemas"]["SchemaContext"];
            /** Table Count */
            table_count: number;
        };
        /** ContextUpdate */
        ContextUpdate: {
            /** Context */
            context: string;
            policy: components["schemas"]["ContextPolicy"];
        };
        /** DatabaseConnectionTestResponse */
        DatabaseConnectionTestResponse: {
            /** Configured */
            configured: boolean;
            current_database?: components["schemas"]["DatabaseSource"] | null;
            /** Message */
            message: string;
            /** Ok */
            ok: boolean;
        };
        /** DatabaseSource */
        DatabaseSource: {
            /** Database */
            database?: string | null;
            /** Fingerprint */
            fingerprint: string;
            /** Host */
            host?: string | null;
            /** Port */
            port?: string | null;
            /**
             * Scanned At
             * Format: date-time
             */
            scanned_at: string;
        };
        /** ExportCreateResponse */
        ExportCreateResponse: {
            /** Byte Count */
            byte_count: number;
            /** Columns */
            columns: string[];
            /** Download Url */
            download_url: string;
            /** Export Id */
            export_id: string;
            /** Row Count */
            row_count: number;
        };
        /** ExportSession */
        ExportSession: {
            approved_intent?: components["schemas"]["CSVIntent"] | null;
            /** Debug Traces */
            debug_traces?: components["schemas"]["SessionDebugTrace"][];
            /** Export Id */
            export_id?: string | null;
            /** Id */
            id: string;
            /** Last Error */
            last_error?: string | null;
            /** Messages */
            messages?: components["schemas"]["ChatMessage"][];
            /** @default drafting_intent */
            status: components["schemas"]["SessionStatus"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Status
             * @default ok
             */
            status: string;
        };
        /** ModelProviderSettingsResponse */
        ModelProviderSettingsResponse: {
            /** Api Key Configured */
            api_key_configured: boolean;
            /** Base Url */
            base_url?: string | null;
            /** Model */
            model: string;
            /** Provider */
            provider: string;
            /** Temperature */
            temperature: number;
        };
        /** ModelProviderSettingsUpdate */
        ModelProviderSettingsUpdate: {
            /** Api Key */
            api_key?: string | null;
            /** Base Url */
            base_url?: string | null;
            /**
             * Model
             * @default openrouter/openai/gpt-4o-mini
             */
            model: string;
            /**
             * Provider
             * @default openrouter
             */
            provider: string;
            /**
             * Temperature
             * @default 0
             */
            temperature: number;
        };
        /** SQLPreparationResponse */
        SQLPreparationResponse: {
            /** Attempts */
            attempts?: components["schemas"]["SQLValidationAttempt"][];
            /** Errors */
            errors?: string[];
            /** Sql */
            sql: string;
            /** Valid */
            valid: boolean;
        };
        /** SQLValidationAttempt */
        SQLValidationAttempt: {
            /** Errors */
            errors?: string[];
            /** Repair Changes */
            repair_changes?: string[];
            /** Sql */
            sql: string;
            /** Valid */
            valid: boolean;
        };
        /** SchemaColumn */
        SchemaColumn: {
            /** Data Type */
            data_type: string;
            /** Default */
            default?: string | null;
            /** Is Nullable */
            is_nullable: boolean;
            /** Name */
            name: string;
            /** Ordinal Position */
            ordinal_position: number;
            /** Sample Values */
            sample_values?: string[];
        };
        /** SchemaContext */
        SchemaContext: {
            /** Relationships */
            relationships?: components["schemas"]["SchemaRelationship"][];
            source?: components["schemas"]["DatabaseSource"] | null;
            /** Tables */
            tables?: components["schemas"]["SchemaTable"][];
        };
        /** SchemaRelationship */
        SchemaRelationship: {
            /** From Columns */
            from_columns: string[];
            /** From Schema */
            from_schema: string;
            /** From Table */
            from_table: string;
            /** To Columns */
            to_columns: string[];
            /** To Schema */
            to_schema: string;
            /** To Table */
            to_table: string;
        };
        /** SchemaTable */
        SchemaTable: {
            /** Columns */
            columns?: components["schemas"]["SchemaColumn"][];
            /** Primary Key */
            primary_key?: string[];
            /** Schema Name */
            schema_name: string;
            /** Table Name */
            table_name: string;
            /** Table Type */
            table_type: string;
        };
        /** SessionCreateResponse */
        SessionCreateResponse: {
            session: components["schemas"]["ExportSession"];
        };
        /** SessionDebugTrace */
        SessionDebugTrace: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Step */
            step: string;
            /** Summary */
            summary: string;
        };
        /** SessionExportRequest */
        SessionExportRequest: {
            /** Sql */
            sql: string;
        };
        /** SessionIntentApprovalRequest */
        SessionIntentApprovalRequest: {
            intent: components["schemas"]["CSVIntent"];
        };
        /** SessionMessageRequest */
        SessionMessageRequest: {
            message: components["schemas"]["ChatMessage"];
        };
        /**
         * SessionStatus
         * @enum {string}
         */
        SessionStatus: "drafting_intent" | "awaiting_approval" | "generating_sql" | "validating_sql" | "exporting" | "complete" | "failed";
        /** SetupCheck */
        SetupCheck: {
            /** Configured */
            configured: boolean;
            /** Message */
            message?: string | null;
            /** Ready */
            ready: boolean;
        };
        /** SetupStatusResponse */
        SetupStatusResponse: {
            context: components["schemas"]["SetupCheck"];
            context_source?: components["schemas"]["DatabaseSource"] | null;
            current_database?: components["schemas"]["DatabaseSource"] | null;
            database: components["schemas"]["SetupCheck"];
            model_provider: components["schemas"]["SetupCheck"];
            /** Next Action */
            next_action?: string | null;
            /** Ready */
            ready: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_context_context_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextDocument"];
                };
            };
        };
    };
    put_context_context_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContextUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextDocument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    scan_context_context_scan_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContextScanResponse"];
                };
            };
        };
    };
    download_export_exports__export_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                export_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    create_session_endpoint_sessions_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionCreateResponse"];
                };
            };
        };
    };
    get_session_endpoint_sessions__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    approve_session_intent_endpoint_sessions__session_id__approve_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionIntentApprovalRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_session_export_endpoint_sessions__session_id__export_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionExportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_session_message_endpoint_sessions__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SessionMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExportSession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prepare_session_sql_endpoint_sessions__session_id__prepare_sql_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SQLPreparationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    propose_session_intent_endpoint_sessions__session_id__propose_intent_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CSVIntentProposal"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_database_settings_endpoint_settings_database_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DatabaseConnectionTestResponse"];
                };
            };
        };
    };
    get_model_provider_settings_endpoint_settings_model_provider_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProviderSettingsResponse"];
                };
            };
        };
    };
    put_model_provider_settings_endpoint_settings_model_provider_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProviderSettingsUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProviderSettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bootstrap_setup_endpoint_setup_bootstrap_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
    get_setup_status_endpoint_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatusResponse"];
                };
            };
        };
    };
}
